version: "3"
services: 
  api:
    build: .
    ports: 
      - 8000:8000
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=767130
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=0a4ce177028f3bb704eb0265583dea509bd4d55da9cb134a9ef20d77d5cdf344
      - ALRORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30